### ISSUE TITLE
Ajout de catégorie

### ISSUE THREAD

**Issue by kesurof** [YggNode/yggnode#22]
Bonjour, est ce qu'il est possible d'ajouter la catégorie 2188 ainsi que les sous catégories (2189,2190 et 219) ?

**Comment by YggNode** [comment]
Hello,

Non pour diverses raisons notamment le contrôle du contenu ou autre : c'est une/des catégories assez sensibles dans le contenu.

**Comment by kesurof** [comment]
merci pour la réponse, dommage c'est la meilleur catégorie pour le ratio
