### ISSUE TITLE
erreur 503

### ISSUE THREAD

**Issue by belette75** [YggNode/yggnode#23]
bonjour,
je pense avoir bien configuré mais ca me remonte ca dans le fichier de log:

WARNING - 20/02/2022 19:08:44 ::   503 Server Error: Service Temporarily Unavailable for url: https://www3.yggtorrent.re/rss?action=generate&type=subcat&id=2171&passkey=TNdVQssYfP3GTDoB3ijgE37c8MVvkASH, retrying in 140 seconds...

**Comment by YggNode** [comment]
Hello,

Aucune idée, mais le but ici n'est pas que chacun déploie son propre système mais plutôt que tout le monde utilise celui déjà en place dans un souci de mutualisation!

Le code n'est publiée qu'à vocation d'analyse / audits / transparence même si à l'origine je pensais le rendre déployable par tout un chacun
