### ISSUE TITLE
ygg domain changed

### ISSUE THREAD

**Issue by Plagouille** [YggNode/yggnode#25]
Not working anymore since ygg has changed to https://yggtorrent.lol/

What a great work. I use it since months. Thanks. I hope it will be back soon.

**Comment by YggNode** [comment]
Je suis banni sans raison, cloudflare me défonce à moitié donc bon ...
S'ils ne veulent pas mettre du leur, ça va s'arrêter là!

**Comment by Plagouille** [comment]
Ha oui je comprends. C'est vraiment dommage. Ces flux RSS sont vraiment utiles mais pas en l'état. Impossible d'y accéder avec des services comme debrid-link ou même IFTTT. Je ne vois pas l'utilité de "protéger" l'accès à un flux RSS avec cloudflare. Contre du DDOS peut-être.

Chez ygg ils ne sont pas ouverts à la discussion ?

Dans tous les cas bravo et merci pour ton service. Puisse-t-il avoir la reconnaissance qu'il mérite ! ☺️ Et continuer d'œuvrer pour notre bien.

**Comment by alexadrien** [comment]
Merci pour ton travail, tous les héros ne portent pas de cape

**Comment by YggNode** [comment]
Je vais essayer de me pencher un peu plus dessus, mais je garantis rien...

Il faudrait que notre scrapper ait un fonctionnement erratique pour imiter un humain, mais même avec ça, ça ne va pas être facile.
Les flux RSS des films et séries précisément sont toujours utilisables mais je n'ai pas eu (pris surtout) le temps de fouiller en profondeur pourquoi.

Il n'y a aucunes notions de protection ou autre, juste qu'ils découvrent que 5000 utilisateurs connectés au site en simultané dont une vingtaine au forum, bah ça fait beaucoup de requêtes par secondes, et vu qu'ils ne veulent pas effectuer aucune amélioration de quelque sorte que ce soit, ils mettent ce surplus de charge sur des attaques DDOS hypothétiques...

Si vraiment les DDOS étaient efficaces, ça ferait longtemps que l'accès au site eut été gelé et qu'une plainte ait été déposée contre cloudflare!

Si vous avez des problèmes ou que vous voyez des gens qui en ont, bah répondez leur ce que vous voulez, que je travaille une peu dessus (mais que j'ai très peu de temps), qu'il n'y a aucunes DDOS, que ça va être temporaire, jsp...

Par ailleurs, même s'ils m'ont ban, je n'en veux pas spécialement à Flop ou Oracle : c'est des bons gars, juste dépassés par le succès du tracker et qui ne se rendent pas compte que YGG même si le nb d'utilisateurs augmente n'est plus aussi attractif qu'avant par rapport à tous les autres qui commencent à avoir des fonctionnalités ultra intéressantes comme notamment sharewood.

Si seulement ils pouvaient se réveiller...
