### ISSUE TITLE
Demande version flaresolverr 

### ISSUE THREAD

**Issue by Bastien42** [YggNode/yggnode#28]
Bonjour je voulais savoir quel version de flaresolverr vous utilisez pour bypass cloudflare pour la récupération des flux RSS car lors de la dernier maj de cf flaresolverr a l'air d'être cassé

https://github.com/FlareSolverr/FlareSolverr/issues/705

Merci pour votre boulot vos RSS on l'aire de toujours refresh

**Comment by YggNode** [comment]
Bonjour,

Les issues ne concernent que yggnode et non flaresolverr ou un système de recherche automatique.

Merci, et oui : ils continueront d'être refresh même si Flop m'a ban.
