### ISSUE TITLE
Ajout qualité

### ISSUE THREAD

**Issue by flunuxx** [YggNode/yggnode#29]
Bonjour,

est il possible d'ajouter la qualité aux rss torrents ?

exemple : category=2145&sub_category=2184&option_qualite%5B%5D=22

option_qualite[]=22 qui correspond a la qualité "WEBrip 4K"

Exemple : https://rss.dathomir.fr:443/rss?id=2184&option_qualite[]=22&passkey=

Merci

**Comment by YggNode** [comment]
Bonjour,

Dans tous les lecteurs de flux RSS "modernes", tu as une option pour faire des regex sur les noms des torrents : C'est à privilégier plutôt que d'implémenter un changement dans le moteur de synchronisation.

Le code actuel (qui a été modifié par rapport à celui présent sur github) est autonome, se suffit à lui même et ne nécessite plus aucune modification (je n'en ai pas effectué depuis 1 an), donc il restera comme ça.
