### ISSUE TITLE
Rss file unavailable for this category at the moment

### ISSUE THREAD

**Issue by ArthurKnoep** [YggNode/yggnode#31]
Even though the status page shows that the categories are fetched quite often (https://rss.dathomir.fr/status), the RSS endpoint is returning this error message: `rss file unavailable for this category at the moment`, with any categories

**Comment by tchirou** [comment]
Some are working : https://rss.dathomir.fr/status
Serie TV is not
Film is

**Comment by ArthurKnoep** [comment]
Indeed I did the test with `Film` and it's working, but `Film/Video` (2145) is not
But for instance `Linux` (2159) is shown to have been synchronised 5 minutes ago and yet the RSS endpoint does not work

**Comment by YggNode** [comment]
Hello,

Pour les 2 :
Tous les fichiers sont stockés en RAM donc à chaque reboot ou autre, tout est effacé et doit être retéléchargé. Tout se fait tout seul mais il faut lui laisser 2H (un timer random est configuré pour "dé-botiser" le comportement").

Vous avez donc dû chopper ces pbs lors d'une phase de reconstruction.

Actuellement tout fonctionne bien nickel:
![image](https://user-images.githubusercontent.com/81962980/232220120-910ce6a1-193e-4af3-b18f-243dad4a0c27.png)

![image](https://user-images.githubusercontent.com/81962980/232220238-4219cc5b-99c1-4576-89ae-e4874b4e741a.png)

Pour le Linux, ils ont changé les Ids des catégories en ajoutant d'autres types dans application, donc je vais aussi devoir le rendre dynamique : Merci pour le retour.

Merci à vous 2 pour la remontée. Merci de fermer l'issue si tout est clair pour vous.

**Comment by ArthurKnoep** [comment]
Ok top merci pour les infos, par contre on vois ta pass key 🙂

**Comment by YggNode** [comment]
un passkey est (sur YGG) un pseudo aléatoire qui n'est valide que s'il est enregistré sur leurs serveurs, or celui ci est du total random donc pas grave.
