### ISSUE TITLE
erreur HTTPConnectionPool

### ISSUE THREAD

**Issue by ghost** [YggNode/yggnode#35]
j'ai installé votre script depuis votre github, cela fonctionne jusqu'au moment ou j'ai cette erreur en boucle

INFO - 13/03/2024 23:54:23 ::   Resync terminated : next in 5.0 mins
DEBUG - 14/03/2024 00:00:02 ::   Server URL : https://**************:443
DEBUG - 14/03/2024 00:00:02 ::   Successfully load categories to sync
DEBUG - 14/03/2024 00:00:02 ::   Starting new HTTPS connection (1): www3.yggtorrent.qa:443
DEBUG - 14/03/2024 00:00:02 ::   https://www3.yggtorrent.qa:443 "GET / HTTP/1.1" 200 None
DEBUG - 14/03/2024 00:00:02 ::   Ygg Response : <Response °200é> 
DEBUG - 14/03/2024 00:00:02 ::    Manual mode enabled 
INFO - 14/03/2024 00:00:02 ::   Process category : 2178
DEBUG - 14/03/2024 00:00:02 ::   Url https://www3.yggtorrent.qa/rss?action=generate&type=subcat&id=2178&passkey=*********************************************
DEBUG - 14/03/2024 00:00:02 ::   Starting new HTTPS connection (1): www3.yggtorrent.qa:443
DEBUG - 14/03/2024 00:00:24 ::   Server URL : https://**************:443
DEBUG - 14/03/2024 00:00:24 ::   Successfully load categories to sync
DEBUG - 14/03/2024 00:00:24 ::   Starting new HTTPS connection (1): www3.yggtorrent.qa:443
DEBUG - 14/03/2024 00:00:24 ::   https://www3.yggtorrent.qa:443 "GET / HTTP/1.1" 200 None
DEBUG - 14/03/2024 00:00:24 ::   Ygg Response : <Response °200é> 
DEBUG - 14/03/2024 00:00:24 ::    Manual mode enabled 
INFO - 14/03/2024 00:00:24 ::   Process category : 2178
DEBUG - 14/03/2024 00:00:24 ::   Url https://www3.yggtorrent.qa/rss?action=generate&type=subcat&id=2178&passkey=*********************************************
DEBUG - 14/03/2024 00:00:24 ::   Starting new HTTPS connection (1): www3.yggtorrent.qa:443
DEBUG - 14/03/2024 00:02:49 ::   Starting new HTTP connection (1): 127.0.0.1:8191
WARNING - 14/03/2024 00:02:49 ::   HTTPConnectionPool(host='127.0.0.1', port=8191): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a5a89b9b0>: Failed to establish a new connection: °Errno 111é Connection refused')), retrying in 320 seconds...
DEBUG - 14/03/2024 00:07:48 ::   http://127.0.0.1:8191à"cmd": "request.get", "url": "https://www3.yggtorrent.qa", "userAgent": "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.1.249.1045 Safari/532.5", "maxTimeout": 60000è
DEBUG - 14/03/2024 00:07:48 ::   Starting new HTTP connection (1): 127.0.0.1:8191
WARNING - 14/03/2024 00:07:48 ::   HTTPConnectionPool(host='127.0.0.1', port=8191): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4f83a84518>: Failed to establish a new connection: °Errno 111é Connection refused')), retrying in 520 seconds...
DEBUG - 14/03/2024 00:08:09 ::   http://127.0.0.1:8191à"cmd": "request.get", "url": "https://www3.yggtorrent.qa", "userAgent": "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.1.249.1045 Safari/532.5", "maxTimeout": 60000è

**Comment by LimeDrive** [comment]
old
