### ISSUE TITLE
Flux RSS Down

### ISSUE THREAD

**Issue by Fr4mby** [YggNode/yggnode#36]
Bonjour,

Il semblerait que les flux RSS soient down depuis ce matin 6h (d'après les logs de mon sonarr).
Visiblement, le status de dernière synchro des flux est vide:
![image](https://github.com/YggNode/yggnode/assets/63785985/38d59d75-fac2-484e-bce3-3ba8566386fd)

**Comment by Bastien42** [comment]
Je confirme, et les liens générés avec Passkey retourne

rss file unavailable for this category at the moment

**Comment by mrmydt** [comment]
Je crois qu'Ygg a changé les ids des catégories. je vois que pour les films par exemple, l'id est 2183 alors qu'il était 2145 auparavant.

**Comment by Bastien42** [comment]
non 2145 c'est le main catégorie de film/vidéo et 2183 c'est la sub catégorie ca la toujours été

**Comment by mrmydt** [comment]
Vu mais trop tard ;-)

**Comment by Fr4mby** [comment]
Visiblement le service a été rétabli. Merci pour ton intervention!

**Comment by Fr4mby** [comment]
Je rouvre le ticket. Même situation que la semaine dernière.
Message "rss file unavailable for this category at the moment" quand on essaie d'accéder aux flux.

**Comment by Bastien42** [comment]
Je confirme le retour du problème

**Comment by DanyDan32** [comment]
Bonjour, je confirme aussi, ça passe plus chez moi ..
Erreur Radarr : "Tous les indexeurs sont indisponibles en raison d'échecs de plus de 6 heures"

**Comment by Bastien42** [comment]
problème a été fix mais depuis 9h a date ne refresh plus les feed rss 
![image](https://github.com/YggNode/yggnode/assets/37946663/45dd780c-28f1-409c-b9e5-aaaa3d7606e1)

**Comment by Fr4mby** [comment]
Même constat de mon côté.

**Comment by Fr4mby** [comment]
Visiblement le souci est réglé. Je ne suis pas sûr qu'une quelconque action ait été effectuée. Chaque fois que les soucis sont réglés, c'est vers 6h du matin. Je soupçonne un reboot d'une VM quotidien qui règle le souci automatiquement :p

**Comment by Bastien42** [comment]
Je pense aussi qu'il n'ont de toute façon pas l'air d'être actif sur le repo donc dommage parce que a ma connaissance c'est le seul moyen de les contacter
