### ISSUE TITLE
Nouveau nom de Domaine le 27/04

### ISSUE THREAD

**Issue by DanyDan32** [YggNode/yggnode#38]
Bonjour,

Pour information sur Rss : 

Pas de mise à jour Rss depuis 5 h maintenant suite au changement du nom de domaine d'Ygg en yggtorrent.cool

**Comment by Fr4mby** [comment]
+1

**Comment by DanyDan32** [comment]
Plus de synchro  ;-(
![1](https://github.com/YggNode/yggnode/assets/165895650/1f470fb0-07dd-4d38-bbe5-51f1de5467fa)

**Comment by Fr4mby** [comment]
Synchro revenue visiblement :)

**Comment by DanyDan32** [comment]
Résolu ce jour !
