### ISSUE TITLE
Cloudflare erreur 403 sur le nouveau domaine ygg.re

### ISSUE THREAD

**Issue by rdmch** [YggNode/yggnode#42]
Hello, 

Super projet !

J'ai tenté de l'acheter sur mon serveur et je me heute à un souci.
J'ai une erreur 403 pour la récup des RSS. 

Connection fails try fix : 403 Client Error: Forbidden for url: https://www3.yggtorrent.cool/rss?action=generate&type=subcat&id=2183&passkey=*********** (ma passkey)

FlareSolver résoud bien mais dès que je fais l'appel suivant ça merde...

DEBUG - 16/05/2024 16:03:08 ::   Server URL : https://yggrss.****************:443
DEBUG - 16/05/2024 16:03:08 ::   Successfully load categories to sync
DEBUG - 16/05/2024 16:03:08 ::   Starting new HTTPS connection (1): www3.yggtorrent.cool:443
DEBUG - 16/05/2024 16:03:08 ::   https://www3.yggtorrent.cool:443 "GET / HTTP/1.1" 403 None
DEBUG - 16/05/2024 16:03:08 ::   Ygg Response : <Response [403]>
INFO - 16/05/2024 16:03:08 ::   Cloudflare UAM enabled
DEBUG - 16/05/2024 16:03:08 ::   http://flaresolverr:8191{"cmd": "request.get", "url": "https://www3.yggtorrent.cool", "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36", "maxTimeout": 60000}
DEBUG - 16/05/2024 16:03:08 ::   Starting new HTTP connection (1): flaresolverr:8191
DEBUG - 16/05/2024 16:03:18 ::   http://flaresolverr:8191 "POST /v1 HTTP/1.1" 200 66954
DEBUG - 16/05/2024 16:03:18 ::    Flaresolverr cookies : {'ygg_': 'ekessfat7upce4o836s9cch*****', 'v19_promo_details': 'eyJjb3VudGRvd25fZGF0ZSI6IjA1LzE2LzIwMjQgMjM6NTk6NTk*****************', 'cf_clearance': 'Jpv9EzOcvoYM0bk21GDn1sC1q7TWti************************'}
INFO - 16/05/2024 16:03:18 ::   Process category : 2183
DEBUG - 16/05/2024 16:03:18 ::   Url https://www3.yggtorrent.cool/rss?action=generate&type=subcat&id=2183&passkey=***************
DEBUG - 16/05/2024 16:03:18 ::   Starting new HTTPS connection (1): www3.yggtorrent.cool:443
DEBUG - 16/05/2024 16:03:18 ::   https://www3.yggtorrent.cool:443 "GET /rss?action=generate&type=subcat&id=2183&passkey=*************** HTTP/1.1" 403 None
WARNING - 16/05/2024 16:03:18 ::   Connection fails try fix : 403 Client Error: Forbidden for url: https://www3.yggtorrent.cool/rss?action=generate&type=subcat&id=2183&passkey=***************
DEBUG - 16/05/2024 16:03:18 ::   http://flaresolverr:8191{"cmd": "request.get", "url": "https://www3.yggtorrent.cool", "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36", "maxTimeout": 60000}
DEBUG - 16/05/2024 16:03:18 ::   Starting new HTTP connection (1): flaresolverr:8191

Je galère... une idée pour moi ?

Bonne journée
RDM

**Comment by LimeDrive** [comment]
#43 


@YggNode Protection du endpoint rss avec un cookie de session `_ygg=`

![rssygg](https://github.com/YggNode/yggnode/assets/82819873/6d19851c-b43c-42b7-9f10-99643ecafe51)

**Comment by LimeDrive** [comment]
Pour info @YggNode, si tu es encore dans le coin,

Voici un exemple d'identification et d'obtention du cookie de session avec CURL :

```bash
curl -F "id=$USER" -F "pass=$PASS" -c cookie.txt https://www.ygg.re/auth/process_login
```

Ensuite, on repasse le cookie de session dans les requêtes pour le flux afin de l'obtenir sans problème. Cependant, il faut noter que désormais, toutes les requêtes seront associées à un compte. Vu les bannissements fréquents, je ne suis pas sûre que cela tienne très longtemps, surtout avec leur volonté de stopper complètement toute automatisation sur leur site.

**Comment by rdmch** [comment]
Bonjour, merci j'avais pas vu vos commentaires. J'ai bien changé le nom de domaine mais rien n'y fait actuellement. Je vois que la partie https://rss.dathomir.fr/ fonctionne. Je suppose que j'ai pas le bon code python pour m'adapter aux dernières nouveautés... Si jamais je suis preneur ! merci :-)

**Comment by LimeDrive** [comment]
Bonjour, 
@rdmch 
Effectivement la mise à jour de ce dépôt n'a pas été faite. Je viens de publier une nouvelle version qui elle ne fait que proxifier une session autorisée sur YGG pour utiliser le RSS de façon personnelle. Le tout tourne autour de Docker et sera beaucoup plus sécurisé au niveau des partages de clés et passkey.

Je publierai une version qui sortira de bêta demain dans la journée. Vous pouvez trouver le dépôt ici : https://github.com/LimeDrive/ygg-rss-proxy

Une discussion avec quelques informations sur la prochaine version :
https://github.com/LimeDrive/ygg-rss-proxy/discussions/3#discussion-6807104

**Comment by rdmch** [comment]
@LimeDrive  Un grand merci. C'est exactement ce qeu je cherche. Je vais regarder ça de plus prêt et basculer sur votre discussion au besoin.
