### ISSUE TITLE
Serveur Down ?

### ISSUE THREAD

**Issue by DanyDan32** [YggNode/yggnode#44]
Bonjour,

Pour information : 
Nous sommes le 25/06 et il n'y a plus de synchronisation des flux YGG

En espérant un retour rapide à la normale
Merci à vous 
Dany

**Comment by Fr4mby** [comment]
Site complètement down et inaccessible de mon côté également.

**Comment by Fr4mby** [comment]
Le site est à nouveau en ligne, mais aucune synchro RSS.

**Comment by Link440** [comment]
Le même pas de flux RSS de dispo

**Comment by DanyDan32** [comment]
4 Flux relancés à l'heure ou j'écris, pas ceux qui m'intéressent certes, mais c'est un bon début ;-)
Linux
MacOS
Windows
Smartphone

**Comment by DanyDan32** [comment]
Tout est rentré dans l'ordre ! 

MILLE MERCIS A L'EQUIPE ! Vous êtes au Top !

**Comment by Fr4mby** [comment]
Merci pour le rétablissement du service :)

**Comment by Link440** [comment]
Ça fonctionne au top !!!
