### ISSUE TITLE
Add category

### ISSUE THREAD

**Issue by Wernouxe** [YggNode/yggnode#47]
There's a category missing, and frankly it's really profitable to make a ratio and follow it up with a feed. I think you know which category I'm talking about (the not very Catholic one, lmao)

It would be great if you could add it, thank you

**Comment by YggNode** [comment]
Ce n'est pas le but de ce projet.

Il a été fait dans un souci de garder accessible les flux RSS en déchargeant le serveur de YGG, pas dans un soucis de taper l'API comme un fils de babouin pour se faire du ratio...
