### ISSUE TITLE
Flux down

### ISSUE THREAD

**Issue by Fr4mby** [YggNode/yggnode#48]
Bonjour,

Les flux sont down depuis ce matin 6h environ.

**Comment by fredthefrenchy** [comment]
Même chose pour moi, plus de flux sur séries et films

**Comment by ulysserevient** [comment]
Idem pour moi ...

**Comment by Fr4mby** [comment]
Réparé visiblement avec le reboot quotidien ;)
Je cloture l'incident du coup.
